name: Mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Install docker compose
      run: sudo apt-get install -y libxml2-dev libxslt-dev python-dev
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --locked --group dev
    - name: Run mypy
      run: uv run mypy
